/* Generated from raw/主路線.csv, raw/次路線.csv and raw/關聯申請.csv. */

const NATIONAL_PARK_ORG_IDS = {
  yushan: "C951CDCD-B75A-46B9-8002-8EF952EC95FD",
  "shei-pa": "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
  taroko: "105E956F-D8DA-49F7-A9B7-3AEFDDA88A12",
};

const ROUTE_DATA = [
    {
        "id":  "np-22",
        "name":  "奇萊主、北峰線",
        "displayName":  "奇萊主、北峰線",
        "originalName":  "奇萊主、北峰線",
        "routeGroup":  "奇萊",
        "routePath":  "",
        "subroute":  "奇萊",
        "agency":  "taroko",
        "agencyName":  "太魯閣國家公園管理處",
        "peak":  "奇萊",
        "days":  1,
        "dayMax":  7,
        "durationLabel":  "1-7 天",
        "diff":  6,
        "status":  "open",
        "hot":  true,
        "image":  "assets/route-qilai.png",
        "note":  "奇萊主北線與奇萊連峰線為（共同承載量）（平日40人、假日60人）。自109年2月21日零時起免辦入山許可證。\r\n",
        "unit":  "taroko",
        "applyType":  "nationalPark",
        "orgId":  "105E956F-D8DA-49F7-A9B7-3AEFDDA88A12",
        "cId":  "22",
        "fId":  "15",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "taroko",
        "requiresNpa":  true,
        "requiresForestCamp":  false,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-23",
        "name":  "奇萊連峰",
        "displayName":  "奇萊連峰",
        "originalName":  "奇萊連峰",
        "routeGroup":  "奇萊",
        "routePath":  "",
        "subroute":  "奇萊",
        "agency":  "taroko",
        "agencyName":  "太魯閣國家公園管理處",
        "peak":  "奇萊",
        "days":  1,
        "dayMax":  4,
        "durationLabel":  "1-4 天",
        "diff":  4,
        "status":  "open",
        "hot":  true,
        "image":  "assets/route-qilai.png",
        "note":  "奇萊主北線與奇萊連峰線為（共同承載量）（平日40人、假日60人）。自109年2月21日零時起免辦入山許可證。\r\n",
        "unit":  "taroko",
        "applyType":  "nationalPark",
        "orgId":  "105E956F-D8DA-49F7-A9B7-3AEFDDA88A12",
        "cId":  "23",
        "fId":  "15",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "taroko",
        "requiresNpa":  true,
        "requiresForestCamp":  false,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-24",
        "name":  "奇萊東稜",
        "displayName":  "奇萊東稜",
        "originalName":  "奇萊東稜",
        "routeGroup":  "奇萊",
        "routePath":  "",
        "subroute":  "奇萊",
        "agency":  "taroko",
        "agencyName":  "太魯閣國家公園管理處",
        "peak":  "奇萊",
        "days":  1,
        "dayMax":  30,
        "durationLabel":  "1-30 天",
        "diff":  6,
        "status":  "open",
        "hot":  true,
        "image":  "assets/route-qilai.png",
        "note":  "自109年2月21日零時起免辦入山許可證。\r\n",
        "unit":  "taroko",
        "applyType":  "nationalPark",
        "orgId":  "105E956F-D8DA-49F7-A9B7-3AEFDDA88A12",
        "cId":  "24",
        "fId":  "15",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "taroko",
        "requiresNpa":  true,
        "requiresForestCamp":  false,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-25",
        "name":  "奇萊南峰",
        "displayName":  "奇萊南峰",
        "originalName":  "奇萊南峰",
        "routeGroup":  "奇萊",
        "routePath":  "",
        "subroute":  "奇萊",
        "agency":  "taroko",
        "agencyName":  "太魯閣國家公園管理處",
        "peak":  "奇萊",
        "days":  1,
        "dayMax":  1,
        "durationLabel":  "單日往返",
        "diff":  1,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-qilai.png",
        "note":  "自109年2月21日零時起免辦入山許可證。\r\n",
        "unit":  "taroko",
        "applyType":  "nationalPark",
        "orgId":  "105E956F-D8DA-49F7-A9B7-3AEFDDA88A12",
        "cId":  "25",
        "fId":  "15",
        "sourceGuid":  "",
        "campId":  "161",
        "relatedCIds":  [
                            "161"
                        ],
        "parkForm":  "taroko",
        "requiresNpa":  true,
        "requiresForestCamp":  true,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-21",
        "name":  "錐麓古道",
        "displayName":  "錐麓古道",
        "originalName":  "錐麓古道",
        "routeGroup":  "錐麓古道",
        "routePath":  "",
        "subroute":  "錐麓古道",
        "agency":  "taroko",
        "agencyName":  "太魯閣國家公園管理處",
        "peak":  "錐麓古道",
        "days":  1,
        "dayMax":  1,
        "durationLabel":  "單日往返",
        "diff":  1,
        "status":  "closed",
        "hot":  true,
        "image":  "assets/route-qilai.png",
        "note":  "*錐麓古道每日開放時間為上午7點進入至下午5點前出登山口，東進東出3.1k原路往返，請於每日上午10點前於錐麓古道售票口查核報到，逾時將不開放進入。 \r\n*錐麓古道行經斷崖該路段請快速通過勿逗留。\r\n*\u003cstrong\u003e錐麓古道不須申請入山證\u003c/strong\u003e。\r\n*\u003cstrong\u003e中橫公路台8線179.5K溪畔災害施工管制，每日上午8時30分至下午5時實施搶修工程施工管制，並於施工管制期間排定有5次放行時段（上午10時、中午11時30分至12時30分、下午2時、下午3時30分、下午5時。實際交管時間請依太魯閣公路段公告為主，若有疑問請洽: 03-9962683），請欲進入錐麓古道的山友留意管制時間，以免通行受阻。\r\n",
        "unit":  "taroko",
        "applyType":  "nationalPark",
        "orgId":  "105E956F-D8DA-49F7-A9B7-3AEFDDA88A12",
        "cId":  "21",
        "fId":  "26",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "taroko",
        "requiresNpa":  true,
        "requiresForestCamp":  false,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  "錐麓古道依舊系統規則暫停入園申請。"
    },
    {
        "id":  "np-132",
        "name":  "錐麓古道（外籍提前）",
        "displayName":  "錐麓古道（外籍提前）",
        "originalName":  "錐麓古道(外籍提前)",
        "routeGroup":  "錐麓古道",
        "routePath":  "",
        "subroute":  "錐麓古道",
        "agency":  "taroko",
        "agencyName":  "太魯閣國家公園管理處",
        "peak":  "錐麓古道",
        "days":  1,
        "dayMax":  1,
        "durationLabel":  "單日往返",
        "diff":  1,
        "status":  "closed",
        "hot":  false,
        "image":  "assets/route-qilai.png",
        "note":  "*錐麓古道每日開放時間為上午7點至下午6點，東進東出3.1k往返需於上午10點前進入。\r\n*近日錐麓古道2.8K有零星落石發生，行經該路段請快速通過勿逗留。\r\n",
        "unit":  "taroko",
        "applyType":  "nationalPark",
        "orgId":  "105E956F-D8DA-49F7-A9B7-3AEFDDA88A12",
        "cId":  "132",
        "fId":  "26",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "taroko",
        "requiresNpa":  true,
        "requiresForestCamp":  false,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  "錐麓古道依舊系統規則暫停入園申請。"
    },
    {
        "id":  "np-26",
        "name":  "南湖大山線",
        "displayName":  "南湖大山線",
        "originalName":  "南湖大山線",
        "routeGroup":  "南湖(南湖大山、中央尖山、北一段)",
        "routePath":  "",
        "subroute":  "南湖(南湖大山、中央尖山、北一段)",
        "agency":  "taroko",
        "agencyName":  "太魯閣國家公園管理處",
        "peak":  "南湖(南湖大山、中央尖山、北一段)",
        "days":  1,
        "dayMax":  30,
        "durationLabel":  "1-30 天",
        "diff":  6,
        "status":  "open",
        "hot":  true,
        "image":  "assets/route-qilai.png",
        "note":  "凡申請南湖大山路線需辦理【警政署入山證】。\r\n警政署入山申辦系統。\r\nhttps://nv2.npa.gov.tw/NM107-604Client/nV01A01Q_01_Action.do?mode=query\u0026method=doList\r\n",
        "unit":  "taroko",
        "applyType":  "nationalPark",
        "orgId":  "105E956F-D8DA-49F7-A9B7-3AEFDDA88A12",
        "cId":  "26",
        "fId":  "16",
        "sourceGuid":  "",
        "campId":  "157",
        "relatedCIds":  [
                            "157",
                            "601"
                        ],
        "parkForm":  "taroko",
        "requiresNpa":  true,
        "requiresForestCamp":  true,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-27",
        "name":  "南湖中央尖 （北一段線）",
        "displayName":  "南湖中央尖（北一段線）",
        "originalName":  "南湖中央尖 (北一段線)",
        "routeGroup":  "南湖(南湖大山、中央尖山、北一段)",
        "routePath":  "",
        "subroute":  "南湖(南湖大山、中央尖山、北一段)",
        "agency":  "taroko",
        "agencyName":  "太魯閣國家公園管理處",
        "peak":  "南湖(南湖大山、中央尖山、北一段)",
        "days":  1,
        "dayMax":  30,
        "durationLabel":  "1-30 天",
        "diff":  6,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-qilai.png",
        "note":  "凡申請南湖中央尖 （北一段線）經過（審馬陣山、南湖北山）等路線需辦理【警政署入山證】。 警政署入山申辦系統。 https://nv2.npa.gov.tw/NM107-604Client/nV01A01Q_01_Action.do?mode=query\u0026method=doList",
        "unit":  "taroko",
        "applyType":  "nationalPark",
        "orgId":  "105E956F-D8DA-49F7-A9B7-3AEFDDA88A12",
        "cId":  "27",
        "fId":  "16",
        "sourceGuid":  "",
        "campId":  "214",
        "relatedCIds":  [
                            "214"
                        ],
        "parkForm":  "taroko",
        "requiresNpa":  true,
        "requiresForestCamp":  true,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-29",
        "name":  "北二段（鬼門關斷崖）",
        "displayName":  "北二段（鬼門關斷崖）",
        "originalName":  "北二段（鬼門關斷崖）",
        "routeGroup":  "北二段（鬼門關斷崖）",
        "routePath":  "",
        "subroute":  "北二段（鬼門關斷崖）",
        "agency":  "taroko",
        "agencyName":  "太魯閣國家公園管理處",
        "peak":  "北二段（鬼門關斷崖）",
        "days":  2,
        "dayMax":  30,
        "durationLabel":  "2-30 天",
        "diff":  6,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-qilai.png",
        "note":  "*請詳閱「北二段路標規劃及施作紀錄表」、「攀登北二段無明西峰至無明山路段注意事項」，並隨時注意天候及路段落石危崖風險。",
        "unit":  "taroko",
        "applyType":  "nationalPark",
        "orgId":  "105E956F-D8DA-49F7-A9B7-3AEFDDA88A12",
        "cId":  "29",
        "fId":  "18",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "taroko",
        "requiresNpa":  true,
        "requiresForestCamp":  false,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-28",
        "name":  "北一段縱走北二段",
        "displayName":  "北一段縱走北二段",
        "originalName":  "北一段縱走北二段",
        "routeGroup":  "北一段縱走北二段",
        "routePath":  "",
        "subroute":  "北一段縱走北二段",
        "agency":  "taroko",
        "agencyName":  "太魯閣國家公園管理處",
        "peak":  "北一段縱走北二段",
        "days":  3,
        "dayMax":  30,
        "durationLabel":  "3-30 天",
        "diff":  6,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-qilai.png",
        "note":  "*請詳閱「北二段路標規劃及施作紀錄表」、「攀登北二段無明西峰至無明山路段注意事項」，並隨時注意天候及路段落石危崖風險。\r\n",
        "unit":  "taroko",
        "applyType":  "nationalPark",
        "orgId":  "105E956F-D8DA-49F7-A9B7-3AEFDDA88A12",
        "cId":  "28",
        "fId":  "17",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "taroko",
        "requiresNpa":  true,
        "requiresForestCamp":  false,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-109",
        "name":  "北一段縱走北二段（南往北）",
        "displayName":  "北一段縱走北二段（南往北）",
        "originalName":  "北一段縱走北二段(南往北)",
        "routeGroup":  "北一段縱走北二段",
        "routePath":  "",
        "subroute":  "北一段縱走北二段",
        "agency":  "taroko",
        "agencyName":  "太魯閣國家公園管理處",
        "peak":  "北一段縱走北二段",
        "days":  3,
        "dayMax":  30,
        "durationLabel":  "3-30 天",
        "diff":  6,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-qilai.png",
        "note":  "*請詳閱「北二段路標規劃及施作紀錄表」、「攀登北二段無明西峰至無明山路段注意事項」，並隨時注意天候及路段落石危崖風險。\r\n",
        "unit":  "taroko",
        "applyType":  "nationalPark",
        "orgId":  "105E956F-D8DA-49F7-A9B7-3AEFDDA88A12",
        "cId":  "109",
        "fId":  "17",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "taroko",
        "requiresNpa":  true,
        "requiresForestCamp":  false,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-35",
        "name":  "清水山",
        "displayName":  "清水山",
        "originalName":  "清水山",
        "routeGroup":  "清水山",
        "routePath":  "",
        "subroute":  "清水山",
        "agency":  "taroko",
        "agencyName":  "太魯閣國家公園管理處",
        "peak":  "清水山",
        "days":  2,
        "dayMax":  7,
        "durationLabel":  "2-7 天",
        "diff":  6,
        "status":  "closed",
        "hot":  false,
        "image":  "assets/route-qilai.png",
        "note":  "*清水山不須申請入山證。",
        "unit":  "taroko",
        "applyType":  "nationalPark",
        "orgId":  "105E956F-D8DA-49F7-A9B7-3AEFDDA88A12",
        "cId":  "35",
        "fId":  "24",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "taroko",
        "requiresNpa":  true,
        "requiresForestCamp":  false,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  "清水山依舊系統規則暫停入園申請。"
    },
    {
        "id":  "np-30",
        "name":  "閂山鈴鳴山",
        "displayName":  "閂山鈴鳴山",
        "originalName":  "閂山鈴鳴山",
        "routeGroup":  "閂山鈴鳴山",
        "routePath":  "",
        "subroute":  "閂山鈴鳴山",
        "agency":  "taroko",
        "agencyName":  "太魯閣國家公園管理處",
        "peak":  "閂山鈴鳴山",
        "days":  1,
        "dayMax":  4,
        "durationLabel":  "1-4 天",
        "diff":  4,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-qilai.png",
        "note":  "*閂山鈴鳴山不須申請入山證。",
        "unit":  "taroko",
        "applyType":  "nationalPark",
        "orgId":  "105E956F-D8DA-49F7-A9B7-3AEFDDA88A12",
        "cId":  "30",
        "fId":  "19",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "taroko",
        "requiresNpa":  true,
        "requiresForestCamp":  false,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-31",
        "name":  "閂山單攻",
        "displayName":  "閂山單攻",
        "originalName":  "閂山單攻",
        "routeGroup":  "閂山單攻",
        "routePath":  "",
        "subroute":  "閂山單攻",
        "agency":  "taroko",
        "agencyName":  "太魯閣國家公園管理處",
        "peak":  "閂山單攻",
        "days":  1,
        "dayMax":  2,
        "durationLabel":  "1-2 天",
        "diff":  2,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-qilai.png",
        "note":  "*閂山不須申請入山證。",
        "unit":  "taroko",
        "applyType":  "nationalPark",
        "orgId":  "105E956F-D8DA-49F7-A9B7-3AEFDDA88A12",
        "cId":  "31",
        "fId":  "20",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "taroko",
        "requiresNpa":  true,
        "requiresForestCamp":  false,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-33",
        "name":  "畢祿山",
        "displayName":  "畢祿山",
        "originalName":  "畢祿山",
        "routeGroup":  "畢祿山",
        "routePath":  "",
        "subroute":  "畢祿山",
        "agency":  "taroko",
        "agencyName":  "太魯閣國家公園管理處",
        "peak":  "畢祿山",
        "days":  1,
        "dayMax":  3,
        "durationLabel":  "1-3 天",
        "diff":  3,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-qilai.png",
        "note":  "*自109年2月21日零時起免辦入山許可證。\r\n",
        "unit":  "taroko",
        "applyType":  "nationalPark",
        "orgId":  "105E956F-D8DA-49F7-A9B7-3AEFDDA88A12",
        "cId":  "33",
        "fId":  "22",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "taroko",
        "requiresNpa":  true,
        "requiresForestCamp":  false,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-34",
        "name":  "羊頭山單攻",
        "displayName":  "羊頭山單攻",
        "originalName":  "羊頭山單攻",
        "routeGroup":  "羊頭山單攻",
        "routePath":  "",
        "subroute":  "羊頭山單攻",
        "agency":  "taroko",
        "agencyName":  "太魯閣國家公園管理處",
        "peak":  "羊頭山單攻",
        "days":  1,
        "dayMax":  1,
        "durationLabel":  "單日往返",
        "diff":  1,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-qilai.png",
        "note":  "*羊頭山單攻不須申請入山證。",
        "unit":  "taroko",
        "applyType":  "nationalPark",
        "orgId":  "105E956F-D8DA-49F7-A9B7-3AEFDDA88A12",
        "cId":  "34",
        "fId":  "23",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "taroko",
        "requiresNpa":  true,
        "requiresForestCamp":  false,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-32",
        "name":  "畢祿縱走羊頭",
        "displayName":  "畢祿縱走羊頭",
        "originalName":  "畢祿縱走羊頭",
        "routeGroup":  "畢祿縱走羊頭",
        "routePath":  "",
        "subroute":  "畢祿縱走羊頭",
        "agency":  "taroko",
        "agencyName":  "太魯閣國家公園管理處",
        "peak":  "畢祿縱走羊頭",
        "days":  1,
        "dayMax":  3,
        "durationLabel":  "1-3 天",
        "diff":  3,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-qilai.png",
        "note":  "*自109年2月21日零時起免辦入山許可證。\r\n",
        "unit":  "taroko",
        "applyType":  "nationalPark",
        "orgId":  "105E956F-D8DA-49F7-A9B7-3AEFDDA88A12",
        "cId":  "32",
        "fId":  "21",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "taroko",
        "requiresNpa":  true,
        "requiresForestCamp":  false,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-55",
        "name":  "其他路線 - 非傳統生態保護區",
        "displayName":  "其他路線 - 非傳統生態保護區",
        "originalName":  "其他（非傳統路線但進入區域屬生態保護區）",
        "routeGroup":  "其他",
        "routePath":  "",
        "subroute":  "其他",
        "agency":  "taroko",
        "agencyName":  "太魯閣國家公園管理處",
        "peak":  "其他",
        "days":  1,
        "dayMax":  30,
        "durationLabel":  "1-30 天",
        "diff":  6,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-qilai.png",
        "note":  "1.若要申請「奇萊南峰」請選擇「奇萊_奇萊南峰」。若要進入南華山及天池周邊，由於該區域不在太魯閣範圍，不用申請入園。\r\n2.若要申請「黃金峽谷」，行程請填寫「三棧社區-三棧南溪-黃金峽谷-三棧南溪-三棧社區」，三棧南溪僅支流黃金峽谷屬本處生態保護區範圍，主流沿線均無需申請本處生態保護區入園許可證。",
        "unit":  "taroko",
        "applyType":  "nationalPark",
        "orgId":  "105E956F-D8DA-49F7-A9B7-3AEFDDA88A12",
        "cId":  "55",
        "fId":  "33",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "taroko",
        "requiresNpa":  true,
        "requiresForestCamp":  false,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-150",
        "name":  "屏風避難山屋申請",
        "displayName":  "屏風避難山屋申請",
        "originalName":  "屏風避難山屋申請",
        "routeGroup":  "屏風避難山屋申請",
        "routePath":  "",
        "subroute":  "屏風避難山屋申請",
        "agency":  "taroko",
        "agencyName":  "太魯閣國家公園管理處",
        "peak":  "屏風避難山屋申請",
        "days":  2,
        "dayMax":  3,
        "durationLabel":  "2-3 天",
        "diff":  3,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-qilai.png",
        "note":  "",
        "unit":  "taroko",
        "applyType":  "nationalPark",
        "orgId":  "105E956F-D8DA-49F7-A9B7-3AEFDDA88A12",
        "cId":  "150",
        "fId":  "37",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "taroko",
        "requiresNpa":  true,
        "requiresForestCamp":  false,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-661",
        "name":  "其他路線 - 南湖大山線",
        "displayName":  "其他路線 - 南湖大山線",
        "originalName":  "其他路線_南湖大山線",
        "routeGroup":  "其他",
        "routePath":  "",
        "subroute":  "其他",
        "agency":  "taroko",
        "agencyName":  "太魯閣國家公園管理處",
        "peak":  "其他",
        "days":  1,
        "dayMax":  30,
        "durationLabel":  "1-30 天",
        "diff":  6,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-qilai.png",
        "note":  "",
        "unit":  "taroko",
        "applyType":  "nationalPark",
        "orgId":  "105E956F-D8DA-49F7-A9B7-3AEFDDA88A12",
        "cId":  "661",
        "fId":  "33",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "taroko",
        "requiresNpa":  true,
        "requiresForestCamp":  false,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-662",
        "name":  "其他路線 - 奇萊群峰",
        "displayName":  "其他路線 - 奇萊群峰",
        "originalName":  "其他路線_奇萊群峰",
        "routeGroup":  "其他",
        "routePath":  "",
        "subroute":  "其他",
        "agency":  "taroko",
        "agencyName":  "太魯閣國家公園管理處",
        "peak":  "其他",
        "days":  1,
        "dayMax":  30,
        "durationLabel":  "1-30 天",
        "diff":  6,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-qilai.png",
        "note":  "",
        "unit":  "taroko",
        "applyType":  "nationalPark",
        "orgId":  "105E956F-D8DA-49F7-A9B7-3AEFDDA88A12",
        "cId":  "662",
        "fId":  "33",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "taroko",
        "requiresNpa":  true,
        "requiresForestCamp":  false,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-3",
        "name":  "玉山前峰單日往返",
        "displayName":  "玉山前峰單日往返",
        "originalName":  "玉山前峰單日往返(塔塔加 - 玉山前峰 - 塔塔加 )",
        "routeGroup":  "玉山線",
        "routePath":  "塔塔加 - 玉山前峰 - 塔塔加",
        "subroute":  "塔塔加 - 玉山前峰 - 塔塔加",
        "agency":  "yushan",
        "agencyName":  "玉山國家公園管理處",
        "peak":  "玉山線",
        "days":  1,
        "dayMax":  1,
        "durationLabel":  "單日往返",
        "diff":  1,
        "status":  "open",
        "hot":  true,
        "image":  "assets/route-yushan.png",
        "note":  "玉山前峰登山口距前峰雖僅0.8公里，但步道坡度較陡，其間有亂石坡，需陡上約360公尺，由海拔約2,877公尺（前峰登山口）登上標高3,239公尺的玉山前峰。單程步行約1.5小時登頂，山頂可眺望玉山主峰及西峰。\r\n本路線往返約需5小時，為安全考量，若自登山口起登3小時仍未抵達玉山前峰者，請一律折返下山。 \r\n\u003ca href=\"https://www.ysnp.gov.tw/Trail/7fa5c242-df1a-4a8e-bcab-32dc55b1f7b6?Tab=5\" target=\"_blank\"\u003e[登山路線路況]\u003c/a\u003e\r\n\u003ca href=\"https://www.ysnp.gov.tw/Highway/C001300\" target=\"_blank\"\u003e[園區路況]\u003c/a\u003e",
        "unit":  "yushan",
        "applyType":  "nationalPark",
        "orgId":  "C951CDCD-B75A-46B9-8002-8EF952EC95FD",
        "cId":  "3",
        "fId":  "1",
        "sourceGuid":  "",
        "campId":  "157",
        "relatedCIds":  [
                            "157",
                            "257",
                            "258",
                            "259"
                        ],
        "parkForm":  "yushan",
        "requiresNpa":  true,
        "requiresForestCamp":  true,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-4",
        "name":  "玉山線單日往返",
        "displayName":  "玉山線單日往返",
        "originalName":  "玉山線單日往返(塔塔加 - 玉山線 - 塔塔加)",
        "routeGroup":  "玉山線",
        "routePath":  "塔塔加 - 玉山線 - 塔塔加",
        "subroute":  "塔塔加 - 玉山線 - 塔塔加",
        "agency":  "yushan",
        "agencyName":  "玉山國家公園管理處",
        "peak":  "玉山線",
        "days":  1,
        "dayMax":  1,
        "durationLabel":  "單日往返",
        "diff":  1,
        "status":  "open",
        "hot":  true,
        "image":  "assets/route-yushan.png",
        "note":  "一、單日往返入園時間原則為上午5時以後，出園時間原則為下午17時以前。為安全考量，上午10時以前未抵達排雲山莊者，請一律折返下山。\r\n二、每年1~3月間因適逢雪季期間，暫停玉山主（西）峰單日往返入園活動。\r\n\u003ca href=\"https://www.ysnp.gov.tw/Trail/7fa5c242-df1a-4a8e-bcab-32dc55b1f7b6?Tab=5\" target=\"_blank\"\u003e[登山路線路況]\u003c/a\u003e\r\n\u003ca href=\"https://www.ysnp.gov.tw/Highway/C001300\" target=\"_blank\"\u003e[園區路況]\u003c/a\u003e",
        "unit":  "yushan",
        "applyType":  "nationalPark",
        "orgId":  "C951CDCD-B75A-46B9-8002-8EF952EC95FD",
        "cId":  "4",
        "fId":  "1",
        "sourceGuid":  "",
        "campId":  "157",
        "relatedCIds":  [
                            "157",
                            "166"
                        ],
        "parkForm":  "yushan",
        "requiresNpa":  true,
        "requiresForestCamp":  true,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-2",
        "name":  "玉山線 2~5天",
        "displayName":  "玉山線 2~5天",
        "originalName":  "2~5天(塔塔加 - 玉山線 - 塔塔加)",
        "routeGroup":  "玉山線",
        "routePath":  "塔塔加 - 玉山線 - 塔塔加",
        "subroute":  "塔塔加 - 玉山線 - 塔塔加",
        "agency":  "yushan",
        "agencyName":  "玉山國家公園管理處",
        "peak":  "玉山線",
        "days":  2,
        "dayMax":  5,
        "durationLabel":  "2-5 天",
        "diff":  5,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-yushan.png",
        "note":  "\u003ca href=\"https://www.ysnp.gov.tw/Trail/7fa5c242-df1a-4a8e-bcab-32dc55b1f7b6?Tab=5\" target=\"_blank\"\u003e[登山路線路況]\u003c/a\u003e\r\n\u003ca href=\"https://www.ysnp.gov.tw/Highway/C001300\" target=\"_blank\"\u003e[園區路況]\u003c/a\u003e",
        "unit":  "yushan",
        "applyType":  "nationalPark",
        "orgId":  "C951CDCD-B75A-46B9-8002-8EF952EC95FD",
        "cId":  "2",
        "fId":  "1",
        "sourceGuid":  "",
        "campId":  "157",
        "relatedCIds":  [
                            "157",
                            "166"
                        ],
        "parkForm":  "yushan",
        "requiresNpa":  true,
        "requiresForestCamp":  true,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-62",
        "name":  "玉山線 2天（外籍提前）",
        "displayName":  "玉山線 2天（外籍提前）",
        "originalName":  "2天(塔塔加 - 玉山線 - 塔塔加)(外籍提前)",
        "routeGroup":  "玉山線",
        "routePath":  "塔塔加 - 玉山線 - 塔塔加",
        "subroute":  "塔塔加 - 玉山線 - 塔塔加",
        "agency":  "yushan",
        "agencyName":  "玉山國家公園管理處",
        "peak":  "玉山線",
        "days":  2,
        "dayMax":  2,
        "durationLabel":  "2 天 1 夜",
        "diff":  2,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-yushan.png",
        "note":  "\u003ca href=\"https://www.ysnp.gov.tw/Trail/7fa5c242-df1a-4a8e-bcab-32dc55b1f7b6?Tab=5\" target=\"_blank\"\u003e[登山路線路況]\u003c/a\u003e\r\n\u003ca href=\"https://www.ysnp.gov.tw/Highway/C001300\" target=\"_blank\"\u003e[園區路況]\u003c/a\u003e",
        "unit":  "yushan",
        "applyType":  "nationalPark",
        "orgId":  "C951CDCD-B75A-46B9-8002-8EF952EC95FD",
        "cId":  "62",
        "fId":  "1",
        "sourceGuid":  "",
        "campId":  "157",
        "relatedCIds":  [
                            "157",
                            "166"
                        ],
        "parkForm":  "yushan",
        "requiresNpa":  true,
        "requiresForestCamp":  true,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-81",
        "name":  "庫哈諾辛山/關山單日往返",
        "displayName":  "庫哈諾辛山/關山單日往返",
        "originalName":  "庫哈諾辛山/關山單日往返(進涇橋/南一段- 庫哈諾辛山／關山 - 進涇橋/南一段)",
        "routeGroup":  "南橫三山-庫哈諾辛山/關山線",
        "routePath":  "進涇橋/南一段- 庫哈諾辛山／關山 - 進涇橋/南一段",
        "subroute":  "進涇橋/南一段- 庫哈諾辛山／關山 - 進涇橋/南一段",
        "agency":  "yushan",
        "agencyName":  "玉山國家公園管理處",
        "peak":  "南橫三山-庫哈諾辛山/關山線",
        "days":  1,
        "dayMax":  1,
        "durationLabel":  "單日往返",
        "diff":  1,
        "status":  "open",
        "hot":  true,
        "image":  "assets/route-yushan.png",
        "note":  "\u003ca href=\"https://www.ysnp.gov.tw/Trail/382f4797-1eb1-4746-a122-4e13a9e0c7e4?Tab=5\" target=\"_blank\"\u003e[登山路線路況]\u003c/a\u003e\r\n\u003ca href=\"https://www.ysnp.gov.tw/Highway/C001300\" target=\"_blank\"\u003e[園區路況]\u003c/a\u003e\r\n一、塔關山、關山嶺山不需辦理入園許可證。\r\n二、南一段行程請選擇「南一段」進出口，關山以南即離開國家公園範圍，請留意入園天數、日期是否選擇正確。\r\n三、台20臨105線（梅山口至向陽）以臨時便道通行，總長44公里，每週一、週三、週五、週六及週日07：00至14：00開放未滿5噸貨車及9人座以下客車、大型重機及機車進出，14：00以後禁止進入，17：00梅山口至向陽路段全線淨空；每週二、週四不開放。",
        "unit":  "yushan",
        "applyType":  "nationalPark",
        "orgId":  "C951CDCD-B75A-46B9-8002-8EF952EC95FD",
        "cId":  "81",
        "fId":  "2",
        "sourceGuid":  "",
        "campId":  "157",
        "relatedCIds":  [
                            "157",
                            "636",
                            "638"
                        ],
        "parkForm":  "yushan",
        "requiresNpa":  true,
        "requiresForestCamp":  true,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-5",
        "name":  "南橫三山-庫哈諾辛山/關山線 2~3天",
        "displayName":  "南橫三山-庫哈諾辛山/關山線 2~3天",
        "originalName":  "2~3天(進涇橋/南一段 - 庫哈諾辛山/關山 - 進涇橋/南一段)",
        "routeGroup":  "南橫三山-庫哈諾辛山/關山線",
        "routePath":  "進涇橋/南一段 - 庫哈諾辛山/關山 - 進涇橋/南一段",
        "subroute":  "進涇橋/南一段 - 庫哈諾辛山/關山 - 進涇橋/南一段",
        "agency":  "yushan",
        "agencyName":  "玉山國家公園管理處",
        "peak":  "南橫三山-庫哈諾辛山/關山線",
        "days":  2,
        "dayMax":  3,
        "durationLabel":  "2-3 天",
        "diff":  3,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-yushan.png",
        "note":  "\u003ca href=\"https://www.ysnp.gov.tw/Trail/382f4797-1eb1-4746-a122-4e13a9e0c7e4?Tab=5\" target=\"_blank\"\u003e[登山路線路況]\u003c/a\u003e\r\n\u003ca href=\"https://www.ysnp.gov.tw/Highway/C001300\" target=\"_blank\"\u003e[園區路況]\u003c/a\u003e\r\n一、塔關山、關山嶺山不需辦理入園許可證。\r\n二、南一段行程請選擇「南一段」進出口，關山以南即離開國家公園範圍，請留意入園天數、日期是否選擇正確。\r\n三、台20臨105線（梅山口至向陽）以臨時便道通行，總長44公里，每週一、週三、週五、週六及週日07：00至14：00開放未滿5噸貨車及9人座以下客車、大型重機及機車進出，14：00以後禁止進入，17：00梅山口至向陽路段全線淨空；每週二、週四不開放。",
        "unit":  "yushan",
        "applyType":  "nationalPark",
        "orgId":  "C951CDCD-B75A-46B9-8002-8EF952EC95FD",
        "cId":  "5",
        "fId":  "2",
        "sourceGuid":  "",
        "campId":  "638",
        "relatedCIds":  [
                            "638",
                            "157",
                            "636"
                        ],
        "parkForm":  "yushan",
        "requiresNpa":  true,
        "requiresForestCamp":  true,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-1",
        "name":  "乙女瀑布單日往返",
        "displayName":  "乙女瀑布單日往返",
        "originalName":  "乙女瀑布單日往返(東埔 – 乙女瀑布 – 東埔)",
        "routeGroup":  "八通關線",
        "routePath":  "東埔 – 乙女瀑布 – 東埔",
        "subroute":  "東埔 – 乙女瀑布 – 東埔",
        "agency":  "yushan",
        "agencyName":  "玉山國家公園管理處",
        "peak":  "八通關線",
        "days":  1,
        "dayMax":  1,
        "durationLabel":  "單日往返",
        "diff":  1,
        "status":  "open",
        "hot":  true,
        "image":  "assets/route-yushan.png",
        "note":  "一、行經東埔至八通關步道2.2K~乙女瀑布沿線仍須特別注意落石、坍塌、路基沖刷、棧橋崩落及倒木等情形。\r\n二、步道沿線的父子斷崖、雲龍瀑布、乙女瀑布等，為遊客所嚮往的景點。為確保遊憩安全，若於中午12時前未抵達乙女瀑布則必須折返。\r\n\u003ca href=\"https://www.ysnp.gov.tw/Trail/e0befc9d-0707-4ce0-b530-6bde521570f9?Tab=5\" target=\"_blank\"\u003e[登山路線路況]\u003c/a\u003e\r\n\u003ca href=\"https://www.ysnp.gov.tw/Highway/C001300\" target=\"_blank\"\u003e[園區路況]\u003c/a\u003e",
        "unit":  "yushan",
        "applyType":  "nationalPark",
        "orgId":  "C951CDCD-B75A-46B9-8002-8EF952EC95FD",
        "cId":  "1",
        "fId":  "28",
        "sourceGuid":  "",
        "campId":  "157",
        "relatedCIds":  [
                            "157",
                            "230"
                        ],
        "parkForm":  "yushan",
        "requiresNpa":  true,
        "requiresForestCamp":  true,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-10",
        "name":  "八通關線 3天",
        "displayName":  "八通關線 3天",
        "originalName":  "3天(東埔 –八通關 – 東埔)",
        "routeGroup":  "八通關線",
        "routePath":  "東埔 –八通關 – 東埔",
        "subroute":  "東埔 –八通關 – 東埔",
        "agency":  "yushan",
        "agencyName":  "玉山國家公園管理處",
        "peak":  "八通關線",
        "days":  3,
        "dayMax":  3,
        "durationLabel":  "3 天 2 夜",
        "diff":  3,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-yushan.png",
        "note":  "一、行經東埔至八通關步道2.2K~12.8K沿線仍須特別注意落石、坍塌、路基沖刷、棧橋崩落及倒木等情形。\r\n二、觀高坪至八通關草原因古道崩坍，仍請高遶通過。\r\n\u003ca href=\"https://www.ysnp.gov.tw/Trail/e0befc9d-0707-4ce0-b530-6bde521570f9?Tab=5\" target=\"_blank\"\u003e[登山路線路況]\u003c/a\u003e\r\n\u003ca href=\"https://www.ysnp.gov.tw/Highway/C001300\" target=\"_blank\"\u003e[園區路況]\u003c/a\u003e",
        "unit":  "yushan",
        "applyType":  "nationalPark",
        "orgId":  "C951CDCD-B75A-46B9-8002-8EF952EC95FD",
        "cId":  "10",
        "fId":  "28",
        "sourceGuid":  "",
        "campId":  "157",
        "relatedCIds":  [
                            "157",
                            "230"
                        ],
        "parkForm":  "yushan",
        "requiresNpa":  true,
        "requiresForestCamp":  true,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-89",
        "name":  "南二段線 2~9天",
        "displayName":  "南二段線 2~9天",
        "originalName":  "2~9天(向陽/東埔 - 南二段 – 東埔/向陽)",
        "routeGroup":  "南二段線",
        "routePath":  "向陽/東埔 - 南二段 – 東埔/向陽",
        "subroute":  "向陽/東埔 - 南二段 – 東埔/向陽",
        "agency":  "yushan",
        "agencyName":  "玉山國家公園管理處",
        "peak":  "南二段線",
        "days":  2,
        "dayMax":  9,
        "durationLabel":  "2-9 天",
        "diff":  6,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-yushan.png",
        "note":  "一、南二段線一般登山行程建議6~7天。\r\n二、行經東埔至八通關步道2.2K~12.8K沿線仍須特別注意落石、坍塌、路基沖刷、棧橋崩落及倒木等情形。\r\n三、觀高坪至八通關草原因古道崩坍，仍請高遶通過。\r\n四、向陽山屋、嘉明湖山屋、向陽山、三叉山、嘉明湖、布新營地、布拉克桑山及戒茂斯等地非本處生態保護區，如需住宿向陽或嘉明湖山屋者，請向林業及自然保育署台東分署提出\u003ca href=\"https://jmlnt.forest.gov.tw/room/\" target=\"_blank\"\u003e申請\u003c/a\u003e。如有本園區域外行程，依進入本園生態保護區日期前2個月為可申請日期，如未依申請期限而有提前申請，將以電子郵件退件通知依申請期限重新提出入園申請。\r\n\r\n\u003ca href=\"https://www.ysnp.gov.tw/Trail/1783c684-3f87-4862-bf4e-e876e639d405?Tab=5\" target=\"_blank\"\u003e[登山路線路況]\u003c/a\u003e\r\n\u003ca href=\"https://www.ysnp.gov.tw/Highway/C001300\" target=\"_blank\"\u003e[園區路況]\u003c/a\u003e",
        "unit":  "yushan",
        "applyType":  "nationalPark",
        "orgId":  "C951CDCD-B75A-46B9-8002-8EF952EC95FD",
        "cId":  "89",
        "fId":  "29",
        "sourceGuid":  "",
        "campId":  "187",
        "relatedCIds":  [
                            "187",
                            "157",
                            "186",
                            "158",
                            "159"
                        ],
        "parkForm":  "yushan",
        "requiresNpa":  true,
        "requiresForestCamp":  true,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-57",
        "name":  "秀姑巒線 4~6天",
        "displayName":  "秀姑巒線 4~6天",
        "originalName":  "4~6天(東埔- 秀姑巒 – 東埔)",
        "routeGroup":  "秀姑巒線",
        "routePath":  "東埔- 秀姑巒 – 東埔",
        "subroute":  "東埔- 秀姑巒 – 東埔",
        "agency":  "yushan",
        "agencyName":  "玉山國家公園管理處",
        "peak":  "秀姑巒線",
        "days":  4,
        "dayMax":  6,
        "durationLabel":  "4-6 天",
        "diff":  6,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-yushan.png",
        "note":  "一、行經東埔至八通關步道2.2K~12.8K沿線仍須特別注意落石、坍塌、路基沖刷、棧橋崩落及倒木等情形。\r\n二、觀高坪至八通關草原因古道崩坍，仍請高遶通過。\r\n\r\n\u003ca href=\"https://www.ysnp.gov.tw/Trail/e0befc9d-0707-4ce0-b530-6bde521570f9?Tab=5\" target=\"_blank\"\u003e[登山路線路況]\u003c/a\u003e\r\n\u003ca href=\"https://www.ysnp.gov.tw/Highway/C001300\" target=\"_blank\"\u003e[園區路況]\u003c/a\u003e",
        "unit":  "yushan",
        "applyType":  "nationalPark",
        "orgId":  "C951CDCD-B75A-46B9-8002-8EF952EC95FD",
        "cId":  "57",
        "fId":  "30",
        "sourceGuid":  "",
        "campId":  "157",
        "relatedCIds":  [
                            "157",
                            "498",
                            "499"
                        ],
        "parkForm":  "yushan",
        "requiresNpa":  true,
        "requiresForestCamp":  true,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-90",
        "name":  "馬博拉斯橫斷線 2~9天",
        "displayName":  "馬博拉斯橫斷線 2~9天",
        "originalName":  "2~9天(東埔/玉里林道–馬博拉斯橫斷–東埔/玉里林道)",
        "routeGroup":  "馬博拉斯橫斷線",
        "routePath":  "東埔/玉里林道–馬博拉斯橫斷–東埔/玉里林道",
        "subroute":  "東埔/玉里林道–馬博拉斯橫斷–東埔/玉里林道",
        "agency":  "yushan",
        "agencyName":  "玉山國家公園管理處",
        "peak":  "馬博拉斯橫斷線",
        "days":  2,
        "dayMax":  9,
        "durationLabel":  "2-9 天",
        "diff":  6,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-yushan.png",
        "note":  "一、馬博拉斯橫斷線一般登山行程建議7天。\r\n二、行經東埔至八通關步道2.2K~12.8K沿線仍須特別注意落石、坍塌、路基沖刷、棧橋崩落及倒木等情形。\r\n三、觀高坪至八通關草原因古道崩坍，仍請高遶通過。\r\n四、太平谷-玉里林道出口非本處所轄園區，不需辦理入園申請。如有本園區域外行程，依進入本園生態保護區日期前2個月為可申請日期，如未依申請期限而有提前申請，將以電子郵件退件通知依申請期限重新提出入園申請。\r\n五、非馬博登山行程將退件，並請另擇八通關、南二段或秀姑巒線申請。\r\n\r\n\u003ca href=\"https://www.ysnp.gov.tw/Trail/8dbb3955-47fc-4311-8077-3518d1ad89b7?Tab=5\" target=\"_blank\"\u003e[登山路線路況]\u003c/a\u003e\r\n\u003ca href=\"https://www.ysnp.gov.tw/Highway/C001300\" target=\"_blank\"\u003e[園區路況]\u003c/a\u003e",
        "unit":  "yushan",
        "applyType":  "nationalPark",
        "orgId":  "C951CDCD-B75A-46B9-8002-8EF952EC95FD",
        "cId":  "90",
        "fId":  "31",
        "sourceGuid":  "",
        "campId":  "199",
        "relatedCIds":  [
                            "199",
                            "157",
                            "198"
                        ],
        "parkForm":  "yushan",
        "requiresNpa":  true,
        "requiresForestCamp":  true,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-61",
        "name":  "新康山線 1~9天",
        "displayName":  "新康山線 1~9天",
        "originalName":  "1~9天(向陽/南安 – 新康橫斷線 – 南安/向陽)",
        "routeGroup":  "新康山線",
        "routePath":  "向陽/南安 – 新康橫斷線 – 南安/向陽",
        "subroute":  "向陽/南安 – 新康橫斷線 – 南安/向陽",
        "agency":  "yushan",
        "agencyName":  "玉山國家公園管理處",
        "peak":  "新康山線",
        "days":  1,
        "dayMax":  9,
        "durationLabel":  "1-9 天",
        "diff":  6,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-yushan.png",
        "note":  "向陽山屋、嘉明湖山屋、向陽山、三叉山、嘉明湖、布新營地、布拉克桑山及戒茂斯等地非本處生態保護區，如需住宿向陽或嘉明湖山屋者，請向林業及自然保育署台東分署提出\u003ca href=\"https://jmlnt.forest.gov.tw/room/\" target=\"_blank\"\u003e申請\u003c/a\u003e。如有本園區域外行程，依進入本園生態保護區日期前2個月為可申請日期，如未依申請期限而有提前申請，將以電子郵件退件通知依申請期限重新提出入園申請。\r\n\u003ca href=\"https://www.ysnp.gov.tw/Trail/ba81933a-a5e2-4ac7-8aa8-d3930c1ec395?Tab=5\" target=\"_blank\"\u003e[登山路線路況]\u003c/a\u003e\r\n\u003ca href=\"https://www.ysnp.gov.tw/Highway/C001300\" target=\"_blank\"\u003e[園區路況]\u003c/a\u003e",
        "unit":  "yushan",
        "applyType":  "nationalPark",
        "orgId":  "C951CDCD-B75A-46B9-8002-8EF952EC95FD",
        "cId":  "61",
        "fId":  "27",
        "sourceGuid":  "",
        "campId":  "158",
        "relatedCIds":  [
                            "158",
                            "159",
                            "157",
                            "573",
                            "571",
                            "572"
                        ],
        "parkForm":  "yushan",
        "requiresNpa":  true,
        "requiresForestCamp":  true,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-51",
        "name":  "八通關越嶺線 3~8天",
        "displayName":  "八通關越嶺線 3~8天",
        "originalName":  "3~8天(南安 - 八通關越嶺線東段 - 南安)",
        "routeGroup":  "八通關越嶺線",
        "routePath":  "南安 - 八通關越嶺線東段 - 南安",
        "subroute":  "南安 - 八通關越嶺線東段 - 南安",
        "agency":  "yushan",
        "agencyName":  "玉山國家公園管理處",
        "peak":  "八通關越嶺線",
        "days":  3,
        "dayMax":  8,
        "durationLabel":  "3-8 天",
        "diff":  6,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-yushan.png",
        "note":  "一、本路線受理佳心至大分入園申請。\r\n二、瓦拉米至大分路段16.3K棧橋損毀、20.1K棧橋損毀、31K至33K有4處坍方路段、32.9K階梯棧橋基座掏空、38K溪谷上切路段約70度異常陡坡需上切。以上路況，請特別評估行程風險並注意通行。\r\n\r\n\u003ca href=\"https://www.ysnp.gov.tw/Trail/e0befc9d-0707-4ce0-b530-6bde521570f9?Tab=5\" target=\"_blank\"\u003e[登山路線路況]\u003c/a\u003e\r\n\u003ca href=\"https://www.ysnp.gov.tw/Highway/C001300\" target=\"_blank\"\u003e[園區路況]\u003c/a\u003e",
        "unit":  "yushan",
        "applyType":  "nationalPark",
        "orgId":  "C951CDCD-B75A-46B9-8002-8EF952EC95FD",
        "cId":  "51",
        "fId":  "32",
        "sourceGuid":  "",
        "campId":  "157",
        "relatedCIds":  [
                            "157",
                            "211"
                        ],
        "parkForm":  "yushan",
        "requiresNpa":  true,
        "requiresForestCamp":  true,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-7",
        "name":  "瓦拉米單日往返",
        "displayName":  "瓦拉米單日往返",
        "originalName":  "瓦拉米單日往返(南安 - 瓦拉米 - 南安)",
        "routeGroup":  "瓦拉米線",
        "routePath":  "南安 - 瓦拉米 - 南安",
        "subroute":  "南安 - 瓦拉米 - 南安",
        "agency":  "yushan",
        "agencyName":  "玉山國家公園管理處",
        "peak":  "瓦拉米線",
        "days":  1,
        "dayMax":  1,
        "durationLabel":  "單日往返",
        "diff":  1,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-yushan.png",
        "note":  "一、山風登山口至東段步道7K里程處尚未進入本處生態保護區，為一般健行步道，不需辦理入園申請。東段步道7K里程處至瓦拉米請提前辦理入園申請。\r\n二、瓦拉米步道單日往返建議行程時間表：\r\n   07：00  步道口出發\r\n   12：00  抵瓦拉米後返程；若未抵瓦拉米者（不論走到哪裡）亦需折返\r\n   16：30  抵步道口（冬季期間）\r\n   17：00  抵步道口（夏季期間）\r\n三、瓦拉米步道係指八通關越嶺線東段，由步道入口經山風－佳心－黃麻至瓦拉米山屋，全長13.6公里的路段。\r\n四、瓦拉米步道3.6K已龜裂滑動、產生落差泥濘達200公尺，通過此區具危險性，請遊客高繞行進並請注意自身安全，快速通過。\u003c/a\u003e\r\n\r\n\u003ca href=\"https://www.ysnp.gov.tw/Trail/e0befc9d-0707-4ce0-b530-6bde521570f9?Tab=5\" target=\"_blank\"\u003e[登山路線路況]\u003c/a\u003e\r\n\u003ca href=\"https://www.ysnp.gov.tw/Highway/C001300\" target=\"_blank\"\u003e[園區路況]\u003c/a\u003e",
        "unit":  "yushan",
        "applyType":  "nationalPark",
        "orgId":  "C951CDCD-B75A-46B9-8002-8EF952EC95FD",
        "cId":  "7",
        "fId":  "3",
        "sourceGuid":  "",
        "campId":  "447",
        "relatedCIds":  [
                            "447",
                            "157"
                        ],
        "parkForm":  "yushan",
        "requiresNpa":  true,
        "requiresForestCamp":  true,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-6",
        "name":  "瓦拉米線 2~3天",
        "displayName":  "瓦拉米線 2~3天",
        "originalName":  "2~3天 (南安 - 瓦拉米 - 南安)",
        "routeGroup":  "瓦拉米線",
        "routePath":  "南安 - 瓦拉米 - 南安",
        "subroute":  "南安 - 瓦拉米 - 南安",
        "agency":  "yushan",
        "agencyName":  "玉山國家公園管理處",
        "peak":  "瓦拉米線",
        "days":  2,
        "dayMax":  3,
        "durationLabel":  "2-3 天",
        "diff":  3,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-yushan.png",
        "note":  "一、山風登山口至東段步道7K里程處尚未進入本處生態保護區，為一般健行步道，不需辦理入園申請。東段步道7K里程處至瓦拉米請提前辦理入園申請。\r\n二、瓦拉米步道3.6K已龜裂滑動、產生落差泥濘達200公尺，通過此區具危險性，請遊客高繞行進並請注意自身安全，快速通過。\r\n\r\n\u003ca href=\"https://www.ysnp.gov.tw/Trail/e0befc9d-0707-4ce0-b530-6bde521570f9?Tab=5\" target=\"_blank\"\u003e[登山路線路況]\u003c/a\u003e\r\n\u003ca href=\"https://www.ysnp.gov.tw/Highway/C001300\" target=\"_blank\"\u003e[園區路況]\u003c/a\u003e",
        "unit":  "yushan",
        "applyType":  "nationalPark",
        "orgId":  "C951CDCD-B75A-46B9-8002-8EF952EC95FD",
        "cId":  "6",
        "fId":  "3",
        "sourceGuid":  "",
        "campId":  "157",
        "relatedCIds":  [
                            "157",
                            "447"
                        ],
        "parkForm":  "yushan",
        "requiresNpa":  true,
        "requiresForestCamp":  true,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-130",
        "name":  "八通關線 其他路線 3~5天",
        "displayName":  "八通關線 其他路線 3~5天",
        "originalName":  "3~5天其他路線(東埔/塔塔加 - 八通關玉山線 - 塔塔加/東埔)",
        "routeGroup":  "八通關線",
        "routePath":  "東埔/塔塔加 - 八通關玉山線 - 塔塔加/東埔",
        "subroute":  "東埔/塔塔加 - 八通關玉山線 - 塔塔加/東埔",
        "agency":  "yushan",
        "agencyName":  "玉山國家公園管理處",
        "peak":  "八通關線",
        "days":  3,
        "dayMax":  5,
        "durationLabel":  "3-5 天",
        "diff":  5,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-yushan.png",
        "note":  "一、八通關至荖濃溪營地2.7K處崩塌已改道，請高繞小心通行。\r\n二、行經東埔至八通關步道2.2K~12.8K沿線仍須特別注意落石、坍塌、路基沖刷、棧橋崩落及倒木等情形。\r\n三、觀高坪至八通關草原因古道崩坍，仍請高遶通過。\r\n四、請上傳登山計畫書。\r\n五、其他路線因非屬既定路線，未規劃有登山步道、指示牌示、安全及住宿設施等人為建物，且為本處非例行性巡查之區域。入園前應自行檢視相關登山行前準備，如體能及技術訓練、路徑判讀及危機處理能力、完善的留守及後援計畫等安全準備事宜。入園時應量力而為，山區路況常面臨崩坍等困難地形、落石或野生物等自然風險，如遇危險或困難，請勿強行通過，並以安全第一為原則，行進間或宿營時應避免破壞原有自然生態環境。另為保存生態保護區原有自然生態環境，其他路線將不因登山活動需求增設相關設施為原則。\r\n\r\n\u003ca href=\"https://www.ysnp.gov.tw/Trail/7fa5c242-df1a-4a8e-bcab-32dc55b1f7b6?Tab=5\" target=\"_blank\"\u003e[玉山線登山路線路況]\u003c/a\u003e\r\n\u003ca href=\"https://www.ysnp.gov.tw/Trail/e0befc9d-0707-4ce0-b530-6bde521570f9?Tab=5\" target=\"_blank\"\u003e[八通關登山路線路況]\u003c/a\u003e\r\n\u003ca href=\"https://www.ysnp.gov.tw/Highway/C001300\" target=\"_blank\"\u003e[園區路況]\u003c/a\u003e",
        "unit":  "yushan",
        "applyType":  "nationalPark",
        "orgId":  "C951CDCD-B75A-46B9-8002-8EF952EC95FD",
        "cId":  "130",
        "fId":  "28",
        "sourceGuid":  "",
        "campId":  "163",
        "relatedCIds":  [
                            "163"
                        ],
        "parkForm":  "yushan",
        "requiresNpa":  true,
        "requiresForestCamp":  true,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-131",
        "name":  "八通關越嶺線 其他路線 4~9天",
        "displayName":  "八通關越嶺線 其他路線 4~9天",
        "originalName":  "4~9天其他路線(南安/東埔 - 八通關越嶺線 – 東埔/南安)",
        "routeGroup":  "八通關越嶺線",
        "routePath":  "南安/東埔 - 八通關越嶺線 – 東埔/南安",
        "subroute":  "南安/東埔 - 八通關越嶺線 – 東埔/南安",
        "agency":  "yushan",
        "agencyName":  "玉山國家公園管理處",
        "peak":  "八通關越嶺線",
        "days":  4,
        "dayMax":  9,
        "durationLabel":  "4-9 天",
        "diff":  6,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-yushan.png",
        "note":  "一、本路線受理佳心至東埔入園申請。\r\n二、瓦拉米至大分路段16.3K棧橋損毀、20.1K棧橋損毀、31K至33K有4處坍方路段、32.9K階梯棧橋基座掏空、38K溪谷上切路段約70度異常陡坡需上切。以上路況，請特別評估行程風險並注意通行。\r\n三、八通關越嶺線，因土葛崩壁等困難地形阻礙，目前有多處路基坍方、無明顯路徑、斷崖或舊有棧橋毀損等路段有風險之虞，需妥為評估行程風險。如仍欲進入八通關越嶺線，全隊人員應對自身及隊伍安全負責，並應自行檢視相關登山行前準備，如體能及技術訓練、路徑判讀及危機處理能力、完善的留守及後援計畫等安全準備事宜。入園時應量力而為，如遇危險或困難請勿強行通過，以安全第一為原則。\r\n四、觀高坪至八通關草原因古道崩坍，仍請高遶通過。\r\n五、行經東埔至八通關步道2.2K~12.8K沿線仍須特別注意落石、坍塌、路基沖刷、棧橋崩落及倒木等情形。\r\n六、請上傳登山計畫書。\r\n\u003ca href=\"https://www.ysnp.gov.tw/Trail/e0befc9d-0707-4ce0-b530-6bde521570f9?Tab=5\" target=\"_blank\"\u003e[登山路線路況]\u003c/a\u003e\r\n\u003ca href=\"https://www.ysnp.gov.tw/Highway/C001300\" target=\"_blank\"\u003e[園區路況]\u003c/a\u003e",
        "unit":  "yushan",
        "applyType":  "nationalPark",
        "orgId":  "C951CDCD-B75A-46B9-8002-8EF952EC95FD",
        "cId":  "131",
        "fId":  "32",
        "sourceGuid":  "",
        "campId":  "157",
        "relatedCIds":  [
                            "157",
                            "210",
                            "211"
                        ],
        "parkForm":  "yushan",
        "requiresNpa":  true,
        "requiresForestCamp":  true,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-128",
        "name":  "其他路線 1~15天",
        "displayName":  "其他路線 1~15天",
        "originalName":  "1~15天(其他路線)",
        "routeGroup":  "其他路線",
        "routePath":  "",
        "subroute":  "其他路線",
        "agency":  "yushan",
        "agencyName":  "玉山國家公園管理處",
        "peak":  "其他路線",
        "days":  1,
        "dayMax":  15,
        "durationLabel":  "1-15 天",
        "diff":  6,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-yushan.png",
        "note":  "一、請上傳登山計畫書。\r\n二、如屬各主路線既定路線行程，將退件請自行選擇既定路線重新申請排隊預約。玉山線其他山峰單日往返請選擇玉山線單日往返申請；八通關玉山線請選擇八通關線申請；南一段行程請選擇庫哈諾辛山/關山線申請；戒茂斯位於國家公園外不需辦理入園申請，戒茂斯攀登新康山線或南二段線，請選擇新康山線或南二段線申請。\r\n三、其他路線因非屬既定路線，未規劃有登山步道、指示牌示、安全及住宿設施等人為建物，且為本處非例行性巡查之區域。入園前應自行檢視相關登山行前準備，如體能及技術訓練、路徑判讀及危機處理能力、完善的留守及後援計畫等安全準備事宜。入園時應量力而為，山區路況常面臨崩坍等困難地形、落石或野生物等自然風險，如遇危險或困難，請勿強行通過，並以安全第一為原則，行進間或宿營時應避免破壞原有自然生態環境。另為保存生態保護區原有自然生態環境，其他路線將不因登山活動需求增設相關設施及維護為原則。\r\n四、如有本園區域外行程，依進入本園生態保護區日期前2個月為可申請日期，如未依申請期限而有提前申請，將以電子郵件退件通知依申請期限重新提出入園申請。\r\n\u003ca href=\"https://www.ysnp.gov.tw/Highway/C001300\" target=\"_blank\"\u003e[園區路況]\u003c/a\u003e",
        "unit":  "yushan",
        "applyType":  "nationalPark",
        "orgId":  "C951CDCD-B75A-46B9-8002-8EF952EC95FD",
        "cId":  "128",
        "fId":  "36",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "yushan",
        "requiresNpa":  true,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "np-97",
        "name":  "七卡、雪山東峰單日往返",
        "displayName":  "七卡、雪山東峰單日往返",
        "originalName":  "(3級)  七卡、雪山東峰單日往返",
        "routeGroup":  "雪山主峰線",
        "routePath":  "",
        "subroute":  "雪山主峰線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "雪山主峰線",
        "days":  1,
        "dayMax":  1,
        "durationLabel":  "單日往返",
        "diff":  3,
        "status":  "open",
        "hot":  true,
        "image":  "assets/route-wuling.png",
        "note":  "",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "97",
        "fId":  "4",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-98",
        "name":  "七卡、雪山東峰",
        "displayName":  "七卡、雪山東峰",
        "originalName":  "(3級)  七卡、雪山東峰",
        "routeGroup":  "雪山主峰線",
        "routePath":  "",
        "subroute":  "雪山主峰線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "雪山主峰線",
        "days":  2,
        "dayMax":  3,
        "durationLabel":  "2-3 天",
        "diff":  3,
        "status":  "open",
        "hot":  true,
        "image":  "assets/route-wuling.png",
        "note":  "",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "98",
        "fId":  "4",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-99",
        "name":  "雪山主峰（多日行程）",
        "displayName":  "雪山主峰（多日行程）",
        "originalName":  "(3級) 雪山主峰(多日行程)",
        "routeGroup":  "雪山主峰線",
        "routePath":  "",
        "subroute":  "雪山主峰線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "雪山主峰線",
        "days":  2,
        "dayMax":  4,
        "durationLabel":  "2-4 天",
        "diff":  3,
        "status":  "open",
        "hot":  true,
        "image":  "assets/route-wuling.png",
        "note":  "",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "99",
        "fId":  "4",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-100",
        "name":  "雪山主峰（單日往返）",
        "displayName":  "雪山主峰（單日往返）",
        "originalName":  "(4級) 雪山主峰(單日往返)",
        "routeGroup":  "雪山主峰線",
        "routePath":  "",
        "subroute":  "雪山主峰線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "雪山主峰線",
        "days":  1,
        "dayMax":  1,
        "durationLabel":  "單日往返",
        "diff":  4,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "100",
        "fId":  "4",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-102",
        "name":  "雪山北峰、翠池",
        "displayName":  "雪山北峰、翠池",
        "originalName":  "(4級) 雪山北峰、翠池",
        "routeGroup":  "雪山主峰線",
        "routePath":  "",
        "subroute":  "雪山主峰線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "雪山主峰線",
        "days":  2,
        "dayMax":  5,
        "durationLabel":  "2-5 天",
        "diff":  4,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "102",
        "fId":  "4",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-103",
        "name":  "雪地訓練申請案",
        "displayName":  "雪地訓練申請案",
        "originalName":  "雪地訓練申請案",
        "routeGroup":  "雪山主峰線",
        "routePath":  "",
        "subroute":  "雪山主峰線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "雪山主峰線",
        "days":  3,
        "dayMax":  10,
        "durationLabel":  "3-10 天",
        "diff":  6,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "103",
        "fId":  "4",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-112",
        "name":  "武陵一秀或二秀 （桃山、池有山） 單日往返",
        "displayName":  "武陵一秀或二秀（桃山、池有山）單日往返",
        "originalName":  "(3級) 武陵一秀或二秀 (桃山、池有山) 單日往返",
        "routeGroup":  "武陵四秀線",
        "routePath":  "",
        "subroute":  "武陵四秀線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "武陵四秀線",
        "days":  1,
        "dayMax":  1,
        "durationLabel":  "單日往返",
        "diff":  3,
        "status":  "open",
        "hot":  true,
        "image":  "assets/route-wuling.png",
        "note":  "",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "112",
        "fId":  "8",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-113",
        "name":  "武陵三秀 （不包含品田山）",
        "displayName":  "武陵三秀（不包含品田山）",
        "originalName":  "(3級) 武陵三秀 (不包含品田山)",
        "routeGroup":  "武陵四秀線",
        "routePath":  "",
        "subroute":  "武陵四秀線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "武陵四秀線",
        "days":  2,
        "dayMax":  3,
        "durationLabel":  "2-3 天",
        "diff":  3,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "113",
        "fId":  "8",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-114",
        "name":  "喀拉業山單日長程往返",
        "displayName":  "喀拉業山單日長程往返",
        "originalName":  "(4級) 喀拉業山單日長程往返",
        "routeGroup":  "武陵四秀線",
        "routePath":  "",
        "subroute":  "武陵四秀線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "武陵四秀線",
        "days":  1,
        "dayMax":  1,
        "durationLabel":  "單日往返",
        "diff":  4,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "114",
        "fId":  "8",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-115",
        "name":  "品田山單日長程往返",
        "displayName":  "品田山單日長程往返",
        "originalName":  "(4級) 品田山單日長程往返",
        "routeGroup":  "武陵四秀線",
        "routePath":  "",
        "subroute":  "武陵四秀線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "武陵四秀線",
        "days":  1,
        "dayMax":  1,
        "durationLabel":  "單日往返",
        "diff":  4,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "115",
        "fId":  "8",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-116",
        "name":  "武陵四秀線",
        "displayName":  "武陵四秀線",
        "originalName":  "(4級) 武陵四秀線",
        "routeGroup":  "武陵四秀線",
        "routePath":  "",
        "subroute":  "武陵四秀線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "武陵四秀線",
        "days":  2,
        "dayMax":  4,
        "durationLabel":  "2-4 天",
        "diff":  4,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "116",
        "fId":  "8",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-156",
        "name":  "秀霸線",
        "displayName":  "秀霸線",
        "originalName":  "(4級) 秀霸線",
        "routeGroup":  "武陵四秀線",
        "routePath":  "",
        "subroute":  "武陵四秀線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "武陵四秀線",
        "days":  3,
        "dayMax":  5,
        "durationLabel":  "3-5 天",
        "diff":  4,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "有危險斷崖地形，請攜帶確保繩索及安全盔。\r\n\r\n",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "156",
        "fId":  "8",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-118",
        "name":  "大霸線",
        "displayName":  "大霸線",
        "originalName":  "(4級) 大霸線",
        "routeGroup":  "大霸線",
        "routePath":  "",
        "subroute":  "大霸線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "大霸線",
        "days":  3,
        "dayMax":  4,
        "durationLabel":  "3-4 天",
        "diff":  4,
        "status":  "open",
        "hot":  true,
        "image":  "assets/route-wuling.png",
        "note":  "",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "118",
        "fId":  "9",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-119",
        "name":  "大霸線（首日住宿中霸山屋）",
        "displayName":  "大霸線（首日住宿中霸山屋）",
        "originalName":  "(5級) 大霸線(首日住宿中霸山屋)",
        "routeGroup":  "大霸線",
        "routePath":  "",
        "subroute":  "大霸線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "大霸線",
        "days":  3,
        "dayMax":  4,
        "durationLabel":  "3-4 天",
        "diff":  5,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "119",
        "fId":  "9",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-155",
        "name":  "馬達拉溪登山口宿營地",
        "displayName":  "馬達拉溪登山口宿營地",
        "originalName":  "(2級) 馬達拉溪登山口宿營地",
        "routeGroup":  "大霸線",
        "routePath":  "",
        "subroute":  "大霸線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "大霸線",
        "days":  2,
        "dayMax":  2,
        "durationLabel":  "2 天 1 夜",
        "diff":  2,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "155",
        "fId":  "9",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-104",
        "name":  "志佳陽大山",
        "displayName":  "志佳陽大山",
        "originalName":  "(3級) 志佳陽大山",
        "routeGroup":  "志佳陽線",
        "routePath":  "",
        "subroute":  "志佳陽線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "志佳陽線",
        "days":  1,
        "dayMax":  3,
        "durationLabel":  "1-3 天",
        "diff":  3,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "請留意天氣變化及司界蘭溪溪水情形，高繞路線非正常步道路徑，應特別注意落石與滑落風險。",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "104",
        "fId":  "5",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-105",
        "name":  "志佳陽-雪山線",
        "displayName":  "志佳陽-雪山線",
        "originalName":  "(4級) 志佳陽-雪山線",
        "routeGroup":  "志佳陽線",
        "routePath":  "",
        "subroute":  "志佳陽線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "志佳陽線",
        "days":  2,
        "dayMax":  4,
        "durationLabel":  "2-4 天",
        "diff":  4,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "請留意天氣變化及司界蘭溪溪水情形，高繞路線非正常步道路徑，應特別注意落石與滑落風險。",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "105",
        "fId":  "5",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-106",
        "name":  "志佳陽-雪山北峰線",
        "displayName":  "志佳陽-雪山北峰線",
        "originalName":  "(5級) 志佳陽-雪山北峰線",
        "routeGroup":  "志佳陽線",
        "routePath":  "",
        "subroute":  "志佳陽線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "志佳陽線",
        "days":  3,
        "dayMax":  5,
        "durationLabel":  "3-5 天",
        "diff":  5,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "請留意天氣變化及司界蘭溪溪水情形，高繞路線非正常步道路徑，應特別注意落石與滑落風險。",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "106",
        "fId":  "5",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-107",
        "name":  "推論山單日往返",
        "displayName":  "推論山單日往返",
        "originalName":  "(3級) 推論山單日往返",
        "routeGroup":  "雪劍線",
        "routePath":  "",
        "subroute":  "雪劍線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "雪劍線",
        "days":  1,
        "dayMax":  1,
        "durationLabel":  "單日往返",
        "diff":  3,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "提醒各位山友，松茂林道高繞路線非常設性步道，通過時應留意四周環境及全隊行進中之安全，更應注意石頭踩落的可能性。雪霸國家公園關心您。\r\n\r\n",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "107",
        "fId":  "6",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-108",
        "name":  "大劍線",
        "displayName":  "大劍線",
        "originalName":  "(4級) 大劍線",
        "routeGroup":  "雪劍線",
        "routePath":  "",
        "subroute":  "雪劍線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "雪劍線",
        "days":  2,
        "dayMax":  3,
        "durationLabel":  "2-3 天",
        "diff":  4,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "提醒各位山友，松茂林道高繞路線非常設性步道，通過時應留意四周環境及全隊行進中之安全，更應注意石頭踩落的可能性。雪霸國家公園關心您。\r\n",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "108",
        "fId":  "6",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-110",
        "name":  "大小劍線",
        "displayName":  "大小劍線",
        "originalName":  "(5級) 大小劍線",
        "routeGroup":  "雪劍線",
        "routePath":  "",
        "subroute":  "雪劍線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "雪劍線",
        "days":  3,
        "dayMax":  4,
        "durationLabel":  "3-4 天",
        "diff":  5,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "提醒各位山友，松茂林道高繞路線非常設性步道，通過時應留意四周環境及全隊行進中之安全，更應注意石頭踩落的可能性。雪霸國家公園關心您。",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "110",
        "fId":  "6",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-111",
        "name":  "雪劍線",
        "displayName":  "雪劍線",
        "originalName":  "(5級) 雪劍線",
        "routeGroup":  "雪劍線",
        "routePath":  "",
        "subroute":  "雪劍線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "雪劍線",
        "days":  4,
        "dayMax":  6,
        "durationLabel":  "4-6 天",
        "diff":  5,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "提醒各位山友，松茂林道高繞路線非常設性步道，通過時應留意四周環境及全隊行進中之安全，更應注意石頭踩落的可能性。雪霸國家公園關心您。",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "111",
        "fId":  "6",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-153",
        "name":  "中雪山、大雪山",
        "displayName":  "中雪山、大雪山",
        "originalName":  "(4級) 中雪山、大雪山",
        "routeGroup":  "雪山西稜線",
        "routePath":  "",
        "subroute":  "雪山西稜線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "雪山西稜線",
        "days":  2,
        "dayMax":  4,
        "durationLabel":  "2-4 天",
        "diff":  4,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "大雪山國家森林遊樂區詳細開放問題請洽東勢林區管理處\u003ca href=\"https://recreation.forest.gov.tw/Forest/RA?typ=0\u0026typ_id=0300003\"\u003ehttps://recreation.forest.gov.tw/Forest/RA?typ=0\u0026typ_id=0300003\u003c/a\u003e。    \r\n230林道注意事項請參考：\u003ca href=\"https://drive.google.com/file/d/1yIp9F8NAZBJ3XKlx-_Dn4GtC0jZglEuA/view?usp=sharing\"\u003ehttps://drive.google.com/file/d/1yIp9F8NAZBJ3XKlx-_Dn4GtC0jZglEuA/view?usp=sharing\u003c/a\u003e（1080821更新） ",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "153",
        "fId":  "7",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-125",
        "name":  "雪山西稜線",
        "displayName":  "雪山西稜線",
        "originalName":  "(5級) 雪山西稜線",
        "routeGroup":  "雪山西稜線",
        "routePath":  "",
        "subroute":  "雪山西稜線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "雪山西稜線",
        "days":  5,
        "dayMax":  8,
        "durationLabel":  "5-8 天",
        "diff":  5,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "大雪山國家森林遊樂區詳細開放問題請洽東勢林區管理處\u003ca href=\"https://recreation.forest.gov.tw/Forest/RA?typ=0\u0026typ_id=0300003\"\u003ehttps://recreation.forest.gov.tw/Forest/RA?typ=0\u0026typ_id=0300003\u003c/a\u003e。    \r\n230林道注意事項請參考：\u003ca href=\"https://drive.google.com/file/d/1yIp9F8NAZBJ3XKlx-_Dn4GtC0jZglEuA/view?usp=sharing\"\u003ehttps://drive.google.com/file/d/1yIp9F8NAZBJ3XKlx-_Dn4GtC0jZglEuA/view?usp=sharing\u003c/a\u003e（1080821更新） ",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "125",
        "fId":  "7",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-121",
        "name":  "聖稜線 I 型",
        "displayName":  "聖稜線 I 型",
        "originalName":  "(5級) 聖稜線I型",
        "routeGroup":  "聖稜線",
        "routePath":  "",
        "subroute":  "聖稜線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "聖稜線",
        "days":  4,
        "dayMax":  6,
        "durationLabel":  "4-6 天",
        "diff":  5,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "有危險斷崖地形，請攜帶確保繩索及安全盔。\r\n\r\n\r\n",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "121",
        "fId":  "11",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-122",
        "name":  "聖稜線 O 型",
        "displayName":  "聖稜線 O 型",
        "originalName":  "(5級) 聖稜線O型",
        "routeGroup":  "聖稜線",
        "routePath":  "",
        "subroute":  "聖稜線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "聖稜線",
        "days":  3,
        "dayMax":  6,
        "durationLabel":  "3-6 天",
        "diff":  5,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "有危險斷崖地形，請攜帶確保繩索及安全盔。",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "122",
        "fId":  "11",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-123",
        "name":  "聖稜線 Y 型",
        "displayName":  "聖稜線 Y 型",
        "originalName":  "(5級) 聖稜線Y型",
        "routeGroup":  "聖稜線",
        "routePath":  "",
        "subroute":  "聖稜線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "聖稜線",
        "days":  4,
        "dayMax":  7,
        "durationLabel":  "4-7 天",
        "diff":  5,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "有危險斷崖地形，請攜帶確保繩索及安全盔。\r\n",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "123",
        "fId":  "11",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-120",
        "name":  "大霸北稜線",
        "displayName":  "大霸北稜線",
        "originalName":  "(5級) 大霸北稜線",
        "routeGroup":  "大霸北稜線",
        "routePath":  "",
        "subroute":  "大霸北稜線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "大霸北稜線",
        "days":  3,
        "dayMax":  5,
        "durationLabel":  "3-5 天",
        "diff":  5,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "120",
        "fId":  "10",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-124",
        "name":  "其他路線 - 傳統路線",
        "displayName":  "其他路線 - 傳統路線",
        "originalName":  "(6級)其他路線(傳統路線)",
        "routeGroup":  "其他路線",
        "routePath":  "",
        "subroute":  "其他路線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "其他路線",
        "days":  1,
        "dayMax":  20,
        "durationLabel":  "1-20 天",
        "diff":  6,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "本路線為既定路線無法符合申請需求時方可使用。需提出登山安全管理表，於申請時一併送件，另請注意公告路線開放狀態。\r\n請注意本路線不可作為一般既定路線使用，送件經審核發現後將予以退件並請重新申請。\r\n\r\n",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "124",
        "fId":  "35",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-666",
        "name":  "自訂路線（非傳統路線）",
        "displayName":  "自訂路線（非傳統路線）",
        "originalName":  "(6級)自訂路線(非傳統路線)",
        "routeGroup":  "其他路線",
        "routePath":  "",
        "subroute":  "其他路線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "其他路線",
        "days":  1,
        "dayMax":  20,
        "durationLabel":  "1-20 天",
        "diff":  6,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "本路線為既定路線無法符合申請需求時方可使用。需提出登山安全管理表，於申請時一併送件，另請注意公告路線開放狀態。\r\n請注意本路線不可作為一般既定路線使用，送件經審核發現後將予以退件並請重新申請。\r\n\r\n",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "666",
        "fId":  "35",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-133",
        "name":  "雪山主峰（多日行程）（外籍提前）",
        "displayName":  "雪山主峰（多日行程）（外籍提前）",
        "originalName":  "(3級) 雪山主峰(多日行程)-\u003c外籍提前\u003e",
        "routeGroup":  "雪山主峰線",
        "routePath":  "",
        "subroute":  "雪山主峰線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "雪山主峰線",
        "days":  2,
        "dayMax":  3,
        "durationLabel":  "2-3 天",
        "diff":  3,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "1.108年9月1日起開放雪山主峰線及大霸線外籍提前申請\r\n2.外籍遊客最早可於入園日前65日至入園日前4個月提出申請，於「臺灣國家公園入園入山線上申請服務網」（英文版）提出申請入園申請及住宿登記。\r\n3.保留七卡山莊、三六九山莊及九九山莊，於每週日至週四（不含國定連續假日）於上述山屋每日各保留24位的名額予外籍登山遊客提前申請。\r\n4.隊伍人數1-5人次得搭配本國籍隊員1位，6-10人次之隊伍則可搭配2位，本國籍每日各山莊保留限額4人，詳細規定請參考「雪霸國家公園生態保護區外籍人士入園申請說明」。",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "133",
        "fId":  "4",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "np-134",
        "name":  "大霸線（外籍提前）",
        "displayName":  "大霸線（外籍提前）",
        "originalName":  "(3級) 大霸線-\u003c外籍提前\u003e",
        "routeGroup":  "大霸線",
        "routePath":  "",
        "subroute":  "大霸線",
        "agency":  "shei-pa",
        "agencyName":  "雪霸國家公園管理處",
        "peak":  "大霸線",
        "days":  3,
        "dayMax":  4,
        "durationLabel":  "3-4 天",
        "diff":  3,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "1.108年9月1日起開放雪山主峰線及大霸線外籍提前申請\r\n2.外籍遊客最早可於入園日前65日至入園日前4個月提出申請，於「臺灣國家公園入園入山線上申請服務網」（英文版）提出申請入園申請及住宿登記。\r\n3.保留七卡山莊、三六九山莊及九九山莊，於每週日至週四（不含國定連續假日）於上述山屋每日各保留24位的名額予外籍登山遊客提前申請。\r\n4.隊伍人數1-5人次得搭配本國籍隊員1位，6-10人次之隊伍則可搭配2位，本國籍每日各山莊保留限額4人，詳細規定請參考「雪霸國家公園生態保護區外籍人士入園申請說明」。",
        "unit":  "shei-pa",
        "applyType":  "nationalPark",
        "orgId":  "E6DD4652-2D37-4346-8F5D-6E538353E0C2",
        "cId":  "134",
        "fId":  "9",
        "sourceGuid":  "",
        "campId":  "0",
        "relatedCIds":  [

                        ],
        "parkForm":  "shei-pa",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  true,
        "requiresSafetyAssessment":  true,
        "suspendReason":  ""
    },
    {
        "id":  "jiaming",
        "name":  "嘉明湖國家步道",
        "displayName":  "嘉明湖國家步道",
        "originalName":  "嘉明湖國家步道",
        "routeGroup":  "林業山屋與營地",
        "routePath":  "向陽 → 向陽山屋 → 嘉明湖",
        "subroute":  "向陽 → 向陽山屋 → 嘉明湖",
        "agency":  "forestry",
        "agencyName":  "林業及自然保育署",
        "peak":  "向陽山 3,603m",
        "days":  3,
        "dayMax":  3,
        "durationLabel":  "3 天 2 夜",
        "diff":  3,
        "status":  "open",
        "hot":  true,
        "image":  "assets/route-nanheng.png",
        "note":  "山屋與營地住宿申請",
        "unit":  "forestry-camp",
        "applyType":  "forestCamp",
        "orgId":  "",
        "cId":  "",
        "fId":  "",
        "sourceGuid":  "",
        "campId":  "",
        "relatedCIds":  [

                        ],
        "parkForm":  "",
        "requiresNpa":  false,
        "requiresForestCamp":  true,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "tianchi",
        "name":  "能高越嶺道 - 天池山莊",
        "displayName":  "能高越嶺道 - 天池山莊",
        "originalName":  "能高越嶺道—天池山莊",
        "routeGroup":  "林業山屋與營地",
        "routePath":  "屯原 → 天池山莊",
        "subroute":  "屯原 → 天池山莊",
        "agency":  "forestry",
        "agencyName":  "林業及自然保育署",
        "peak":  "天池山莊 2,860m",
        "days":  2,
        "dayMax":  2,
        "durationLabel":  "2 天 1 夜",
        "diff":  2,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-qilai.png",
        "note":  "山屋住宿申請",
        "unit":  "forestry-camp",
        "applyType":  "forestCamp",
        "orgId":  "",
        "cId":  "",
        "fId":  "",
        "sourceGuid":  "",
        "campId":  "",
        "relatedCIds":  [

                        ],
        "parkForm":  "",
        "requiresNpa":  false,
        "requiresForestCamp":  true,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "guigu",
        "name":  "檜谷山屋（北大武）",
        "displayName":  "檜谷山屋（北大武）",
        "originalName":  "檜谷山屋（北大武）",
        "routeGroup":  "林業山屋與營地",
        "routePath":  "登山口 → 檜谷山莊 → 北大武",
        "subroute":  "登山口 → 檜谷山莊 → 北大武",
        "agency":  "forestry",
        "agencyName":  "林業及自然保育署",
        "peak":  "北大武山 3,092m",
        "days":  2,
        "dayMax":  2,
        "durationLabel":  "2 天 1 夜",
        "diff":  3,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-qilai.png",
        "note":  "山屋住宿申請",
        "unit":  "forestry-camp",
        "applyType":  "forestCamp",
        "orgId":  "",
        "cId":  "",
        "fId":  "",
        "sourceGuid":  "",
        "campId":  "",
        "relatedCIds":  [

                        ],
        "parkForm":  "",
        "requiresNpa":  false,
        "requiresForestCamp":  true,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "walami",
        "name":  "瓦拉米山屋",
        "displayName":  "瓦拉米山屋",
        "originalName":  "瓦拉米山屋",
        "routeGroup":  "林業山屋與營地",
        "routePath":  "南安 → 瓦拉米山屋",
        "subroute":  "南安 → 瓦拉米山屋",
        "agency":  "forestry",
        "agencyName":  "林業及自然保育署",
        "peak":  "瓦拉米 1,068m",
        "days":  2,
        "dayMax":  2,
        "durationLabel":  "2 天 1 夜",
        "diff":  2,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-nanheng.png",
        "note":  "山屋住宿申請",
        "unit":  "forestry-camp",
        "applyType":  "forestCamp",
        "orgId":  "",
        "cId":  "",
        "fId":  "",
        "sourceGuid":  "",
        "campId":  "",
        "relatedCIds":  [

                        ],
        "parkForm":  "",
        "requiresNpa":  false,
        "requiresForestCamp":  true,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "police-yushan",
        "name":  "玉山地區入山許可",
        "displayName":  "玉山地區入山許可",
        "originalName":  "玉山地區入山許可",
        "routeGroup":  "警政署入山許可",
        "routePath":  "玉山國家公園範圍",
        "subroute":  "玉山國家公園範圍",
        "agency":  "police",
        "agencyName":  "警政署",
        "peak":  "入山證",
        "days":  1,
        "dayMax":  1,
        "durationLabel":  "單日",
        "diff":  2,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-yushan.png",
        "note":  "入山許可",
        "unit":  "police",
        "applyType":  "summary",
        "orgId":  "",
        "cId":  "",
        "fId":  "",
        "sourceGuid":  "",
        "campId":  "",
        "relatedCIds":  [

                        ],
        "parkForm":  "",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    },
    {
        "id":  "police-shei-pa",
        "name":  "雪霸地區入山許可",
        "displayName":  "雪霸地區入山許可",
        "originalName":  "雪霸地區入山許可",
        "routeGroup":  "警政署入山許可",
        "routePath":  "雪霸國家公園範圍",
        "subroute":  "雪霸國家公園範圍",
        "agency":  "police",
        "agencyName":  "警政署",
        "peak":  "入山證",
        "days":  1,
        "dayMax":  1,
        "durationLabel":  "單日",
        "diff":  2,
        "status":  "open",
        "hot":  false,
        "image":  "assets/route-wuling.png",
        "note":  "入山許可",
        "unit":  "police",
        "applyType":  "summary",
        "orgId":  "",
        "cId":  "",
        "fId":  "",
        "sourceGuid":  "",
        "campId":  "",
        "relatedCIds":  [

                        ],
        "parkForm":  "",
        "requiresNpa":  false,
        "requiresForestCamp":  false,
        "requiresAttachment":  false,
        "requiresSafetyAssessment":  false,
        "suspendReason":  ""
    }
];

const AGENCIES = [
  { id: "all", name: "全部", icon: "ph-bold ph-mountains" },
  { id: "yushan", name: "玉山國家公園", icon: "ph-bold ph-mountains" },
  { id: "shei-pa", name: "雪霸國家公園", icon: "ph-bold ph-mountains" },
  { id: "taroko", name: "太魯閣國家公園", icon: "ph-bold ph-mountains" },
  { id: "forestry", name: "林業及自然保育署", icon: "ph-bold ph-tree" },
  { id: "police", name: "警政署 入山許可", icon: "ph-bold ph-shield-check" },
];

const AGENCY_DESC = {
  yushan: "玉山國家公園管理處核發入園證，部分路線需抽籤、住宿或附件審核。",
  "shei-pa": "雪霸國家公園管理處核發入園證，依路線分級檢核隊伍能力與安全計畫。",
  taroko: "太魯閣國家公園管理處核發入園證，依承載量、宿營地與路線節點控管。",
  forestry: "林業及自然保育署管轄之山屋與營地申請，例如嘉明湖、天池、檜谷等。",
  police: "進入山地管制區或國家公園範圍另需警政署入山許可。",
};

Object.assign(window, { ROUTE_DATA, AGENCIES, AGENCY_DESC, NATIONAL_PARK_ORG_IDS });
